name: instr_timing

env:
  ZIG_VERSION: 0.11.0

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: instr_timing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install libsixel
        run: |
          sudo apt update
          sudo apt install -y libsixel-dev

      - name: Install zig
        run: |
          curl https://ziglang.org/builds/zig-linux-x86_64-${{env.ZIG_VERSION}}.tar.xz -L -o zig.tar.xz
          tar -xf zig.tar.xz
          echo "$(pwd)/zig-linux-x86_64-${{env.ZIG_VERSION}}" >> $GITHUB_PATH

      - name: Get Free BootROM
        run: |
          curl \
            https://github.com/take44444/Gameboy-free_bootrom/releases/download/1.0.0/dmg_bootrom.bin \
            -L \
            -o dmg_bootrom.bin

      - name: Get Test Cartridge
        run: |
          curl \
            https://raw.githubusercontent.com/retrio/gb-test-roms/master/instr_timing/instr_timing.gb \
            -L \
            -o instr_timing.gb

      - name: Run tests
        run: |
          timeout 120 \
            zig build run -- \
              --no-graphics \
              --bootrom=./dmg_bootrom.bin \
              --cart=./instr_timing.gb \
              --exit_at=6F3 \
              --dump_vram=./test.vram
          diff ./test.vram ./tests/assets/instr_timing.vram
